name: 1.0$(Rev:.r)
trigger:
- main

pool:
  name: Default
  demands: 
    - agent.name -equals OCRA 

variables:
  buildConfiguration: 'Release'
  artifactName: 'TodoDatabase'

steps:
- task: CopyFiles@2
  displayName: 'Copy cicd scripts to: $(Build.ArtifactStagingDirectory)\scripts'
  inputs:
    SourceFolder: .\cicd
    Contents: '*.ps1'
    TargetFolder: $(Build.ArtifactStagingDirectory)\scripts

- task: PublishPipelineArtifact@1
  displayName: Publish Pipeline Artifact scripts
  inputs:
    artifactName: scripts
    targetPath: $(Build.ArtifactStagingDirectory)/scripts

- task: MSBuild@1
  displayName: 'Build database project $(ArtifactName)'
  inputs:
    configuration: $(buildConfiguration)
    solution: $(ArtifactName)\$(ArtifactName).sqlproj
    msbuildArguments: /p:OutputPath="$(Build.ArtifactStagingDirectory)/"

- task: PublishPipelineArtifact@1
  displayName: Publish Pipeline Artifact $(ArtifactName).dacpac
  inputs:
    artifactName: $(ArtifactName)
    targetPath: $(Build.ArtifactStagingDirectory)/$(ArtifactName).dacpac